### ISSUE TITLE
 Property 'children' does not exist on type 'IntrinsicAttributes & JitsuProviderProps'.

### ISSUE THREAD

**Issue by cs224** [jitsucom/jitsu-js#5]
Hello, I am trying to do the following:

```
<JitsuProvider client={jitsuClient}>
  <GrowthBookProvider growthbook={growthbook}>
    {p.children}
  </GrowthBookProvider>
</JitsuProvider>
```

and I get an error: Property 'children' does not exist on type 'IntrinsicAttributes & JitsuProviderProps'.

I guess the issue could be solved in `https://github.com/jitsucom/jitsu-js/blob/master/packages/nextjs/src/JitsuProvider.tsx` by using `PropsWithChildren`:

```
const JitsuProvider: React.FC<PropsWithChildren<JitsuProviderProps>> = function ({children, client}) {
  const Context = JitsuContext
  return <Context.Provider value={client}>{children}</Context.Provider>
}
```

Thanks,
Christian

**Comment by vklimontovich** [comment]
Yes, seems like that! Let us take look. Would you mind sharing what version of React / nextjs are you using?

P. S. We have a separate framework for Next.js, which is currently in `beta`: https://github.com/jitsucom/next-collect

**Comment by vklimontovich** [comment]
Would you please try `3.1.2`?

**Comment by cs224** [comment]
Thank you very much for the quick fix. This worked. I'll also have a look at next-collect. Thanks!
