### ISSUE TITLE
set is not a function

### ISSUE THREAD

**Issue by bay-jacewhitten** [jitsucom/jitsu-js#6]
It appears that 'set' is not being exported. I can see the type definition, but when I break over the object, I do not see it in the list of available functions

console error I get is `set is not a function`

![Screen Shot 2022-06-29 at 12 30 41 PM](https://user-images.githubusercontent.com/79159096/176520397-f3ee581b-513c-43fd-80dd-731c38305558.png)

Using =>

react:  18+
@jistsu/react: 3.1.2

**Comment by absorbb** [comment]
@bay-jacewhitten 
Thank you for reporting that. Fixed in @jitsu/react: 3.1.3
Please try it

**Comment by bay-jacewhitten** [comment]
This is no longer reporting an error in the console and is 'setting' the properties object as expected. This issue is now closed.

Thank you for the quick update and hard work!
