### ISSUE TITLE
Next.js 13 support

### ISSUE THREAD

**Issue by ddanielgal** [jitsucom/jitsu-js#9]
Hello,

We are migrating our app to Next.js version 13, and `@jitsu/nextjs` is the only dependency that does not have Next.js 13 as a supported peer dependency.

Are there any plans or ongoing work on supporting Next.js 13 in `@jitsu/nextjs`?

I have tried out the library in our app using the `--legacy-peer-deps` flag on npm install, and I have not found any errors with it so far. I believe that Next.js 13 is ready to be added as a peer dependency.

If there are no objections, I will prepare a pull request allowing Next.js 13 as a peer dependency for the `@jitsu/nextjs` library.

**Comment by nandanrao** [comment]
Hi all - what's the status on this? I would like to use this with NextJS 14 now as well :) Happy to add to the PR, but just want to understand the process.

**Comment by nubcake94** [comment]
> Hi all - what's the status on this? I would like to use this with NextJS 14 now as well :) Happy to add to the PR, but just want to understand the process. 

My PR is still open on nextjs 13 😿
This repo doesnt seem to be maintained. We ended up forking it and we continued using that
